function [X, F] = run_hrea_mmf4(N, maxFE)
    clc;

    %% 添加 PlatEMO 路径
    addpath(genpath('D:\Project\PlatEMO\PlatEMO\PlatEMO'));

    N = double(N);
    maxFE = double(maxFE);

    %% 调用 PlatEMO
    [X, F] = platemo( ...
        'algorithm', @HREA, ...
        'problem',   @MMF4, ...
        'N',         N, ...
        'maxFE',     maxFE, ...
        'draw',      false ...
    );
end
