function [X, F] = run_mmeapsl_mmf5(N, maxFE)
    clc;

    %% 添加 PlatEMO 路径
    addpath(genpath('D:\Project\PlatEMO\PlatEMO\PlatEMO'));

    N = double(N);
    maxFE = double(maxFE);

    %% 调用 PlatEMO
    [X, F] = platemo( ...
        'algorithm', @MMEAPSL, ...
        'problem',   @MMF5, ...
        'N',         N, ...
        'maxFE',     maxFE, ...
        'draw',      false, ...
        'silent',    true ...
    );
end
